export const leagues = {
    FETCHING_STANDINGS: 'FETCHING_STANDINGS',
    FETCHING_STANDINGS_ERROR: 'FETCHING_STANDINGS_ERROR',
    STANDINGS_FETCHED: 'STANDINGS_FETCHED',

    FETCHING_TEAMS: 'FETCHING_TEAMS',
    FETCHING_TEAMS_ERROR: 'FETCHING_TEAMS_ERROR',
    TEAMS_FETCHED: 'TEAMS_FETCHED',
};

export const favorites = {
    ADD_FAVORITE_TEAM: 'ADD_FAVORITE_TEAM',
    DELETE_FAVORITE_TEAM: 'DELETE_FAVORITE_TEAM',
};

export const activeLeague = {
    CHANGE_ACTIVE_LEAGUE: 'CHANGE_ACTIVE_LEAGUE',
};

export const activePage = {
    CHANGE_ACTIVE_PAGE: 'CHANGE_ACTIVE_PAGE',
};

export const current = {
    FETCHING_ONE_TEAM: 'FETCHING_ONE_TEAM',
    FETCHING_ONE_TEAM_ERROR: 'FETCHING_ONE_TEAM_ERROR',
    ONE_TEAM_FETCHED: 'ONE_TEAM_FETCHED',
    DELETE_CURRENT_TEAM: 'DELETE_CURRENT_TEAM',
};

export const TOGGLE_SHOWING_FAVORITES = 'TOGGLE_SHOWING_FAVORITES';

export const TOGGLE_PLAYERS_FIXTURES = 'TOGGLE_PLAYERS_FIXTURES';

export const teamInfoPagination = {
    GO_TO_NEXT: 'GO_TO_NEXT',
    GO_TO_PREV: 'GO_TO_PREV',
    GO_TO_LAST: 'GO_TO_LAST',
    GO_TO_FIRST: 'GO_TO_FIRST',
    CHANGE_COUNT_PER_PAGE: 'CHANGE_COUNT_PER_PAGE',
    SET_PAGES_NUMBER: 'SET_PAGES_NUMBER',
    SET_PAGINATED: 'SET_PAGINATED',
    CLEAR_PAGINATION: 'CLEAR_PAGINATION',
};

export const fixtDetails = {
    FETCHING_FIXTURE_DETAILS: 'FETCHING_FIXTURE_DETAILS',
    FETCHING_FIXTURE_DETAILS_ERROR: 'FETCHING_FIXTURE_DETAILS_ERROR',
    FIXTURE_DETAILS_FETCHED: 'FIXTURE_DETAILS_FETCHED',
    UPDATE_DETAILS: 'UPDATE_DETAILS',
    CLEAR_DETAILS: 'CLEAR_DETAILS',
};
