export const leagues = {
    FETCHING_STANDINGS: 'FETCHING_STANDINGS',
    FETCHING_STANDINGS_ERROR: 'FETCHING_STANDINGS_ERROR',
    STANDINGS_FETCHED: 'STANDINGS_FETCHED',

    FETCHING_TEAMS: 'FETCHING_TEAMS',
    FETCHING_TEAMS_ERROR: 'FETCHING_TEAMS_ERROR',
    TEAMS_FETCHED: 'TEAMS_FETCHED',

    ADD_FAVORITE_TEAM: 'ADD_FAVORITE_TEAM',
    DELETE_FAVORITE_TEAM: 'DELETE_FAVORITE_TEAM',
};

export const activeLeague = {
    CHANGE_ACTIVE_LEAGUE: 'CHANGE_ACTIVE_LEAGUE',
};

export const activePage = {
    CHANGE_ACTIVE_PAGE: 'CHANGE_ACTIVE_PAGE',
};

export const TOGGLE_SHOWING_FAVORITES = 'TOGGLE_SHOWING_FAVORITES';
