export const favoriteTeams = {
    ADD_FAVORITE_TEAM: 'ADD_FAVORITE_TEAM',
    DELETE_FAVORITE_TEAM: 'DELETE_FAVORITE_TEAM',

    FETCHING_FAVORITE_TEAMS: 'FETCHING_FAVORITE_TEAMS',
    FETCHING_FAVORITE_TEAMS_ERROR: 'FETCHING_FAVORITE_TEAMS_ERROR',
    FAVORITE_TEAMS_FETCHED: 'FAVORITE_TEAMS_FETCHED',
};

export const leagues = {
    FETCHING_STANDINGS: 'FETCHING_STANDINGS',
    FETCHING_STANDINGS_ERROR: 'FETCHING_STANDINGS_ERROR',
    STANDINGS_FETCHED: 'STANDINGS_FETCHED',

    FETCHING_TEAMS: 'FETCHING_TEAMS',
    FETCHING_TEAMS_ERROR: 'FETCHING_TEAMS_ERROR',
    TEAMS_FETCHED: 'TEAMS_FETCHED',
};

export const activeLeague = {
    CHANGE_ACTIVE_LEAGUE: 'CHANGE_ACTIVE_LEAGUE',
};
